url: https://baojuanwang.github.io
baseurl: ""
footer_text: >
  Powered by Jekyll with the al-folio theme. Hosted by GitHub Pages.
search_enabled: false
enable_darkmode: false
enable_progressbar: false
navbar_fixed: false
